name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Or your preferred Node.js version

      - name: Install dependencies
        run: npm install  # Or yarn install

      - name: Build React app
        run: npm run build  # Or yarn build

      - name: Update index.html with new file names  # New step added here
        run: |
          # Get the new JS and CSS file names
          JS_FILE=$(ls dist/assets/index-*.js)
          CSS_FILE=$(ls dist/assets/index-*.css)
          # Update the index.html file
          sed -i "s/src=\".*index-.*\.js\"/src=\"$JS_FILE\"/" dist/index.html
          sed -i "s/href=\".*index-.*\.css\"/href=\"$CSS_FILE\"/" dist/index.html

      - name: Setup SSH deploy key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
