name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build  # or yarn build if you use Yarn

      - name: Copy CSS File to Correct Location
        run: |
          if [[ -f "src/index.css" ]]; then
            cp src/index.css dist/index.css  # Copy to dist/ instead of dist/assets/
            echo "CSS file copied successfully to dist/"
          else
            echo "Error: src/index.css not found!"
            exit 1
          fi

      - name: Update index.html with new file names
        run: |
          # Capture your hashed JS/CSS filenames from dist/assets/
          JS_FILE=$(ls dist/assets/*.js | head -n 1)
          CSS_FILE="index.css"  # CSS is now in dist/, so no need to look in dist/assets/

          # Check if files were found
          if [[ -z "$JS_FILE" ]]; then
            echo "Error: JS file not found in dist/assets/"
            exit 1
          fi
          if [[ ! -f "dist/index.css" ]]; then
            echo "Error: CSS file not found in dist/"
            exit 1
          fi

          # Use '|' as the sed delimiter to avoid errors with '-' or '/' in filenames
          sed -i "s|src=\".*\\.js\"|src=\"$JS_FILE\"|" dist/index.html
          sed -i "s|href=\".*\\.css\"|href=\"./index.css\"|" dist/index.html

      - name: Setup SSH deploy key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # <--- pushes to gh-pages
          publish_dir: ./dist       # <--- what folder to publish
