name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change if your default branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Or whatever Node version you need

      - name: Install dependencies
        run: npm install  # Or yarn install

      - name: Build React app
        run: npm run build  # Or yarn build

      - name: Update index.html with new file names
        run: |
          # Capture the hashed JS and CSS filenames from dist/assets/
          JS_FILE=$(ls dist/assets/index-*.js)
          CSS_FILE=$(ls dist/assets/index-*.css)

          # Use '|' as the sed delimiter to avoid conflicts with dashes/slashes
          sed -i "s|src=\".*index-.*\\.js\"|src=\"$JS_FILE\"|" dist/index.html
          sed -i "s|href=\".*index-.*\\.css\"|href=\"$CSS_FILE\"|" dist/index.html

      - name: Setup SSH deploy key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
